//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xilytix.FieldedText.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xilytix.FieldedText.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean Text &quot;{0}&quot; does not match True or False text..
        /// </summary>
        internal static string BooleanFieldFormatter_Parse_NoMatch {
            get {
                return ResourceManager.GetString("BooleanFieldFormatter_Parse_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DateTime value: &quot;{0}&quot;.
        /// </summary>
        internal static string DateTimeFieldFormatter_Parse_Invalid {
            get {
                return ResourceManager.GetString("DateTimeFieldFormatter_Parse_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime formatting error: {0}.
        /// </summary>
        internal static string DateTimeFieldFormatter_ToText_ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("DateTimeFieldFormatter_ToText_ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime formatting error: {0}.
        /// </summary>
        internal static string DateTimeFieldFormatter_ToText_Format {
            get {
                return ResourceManager.GetString("DateTimeFieldFormatter_ToText_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Decimal value: &quot;{0}&quot;.
        /// </summary>
        internal static string DecimalFieldFormatter_Parse_Invalid {
            get {
                return ResourceManager.GetString("DecimalFieldFormatter_Parse_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal formatting error: {0}.
        /// </summary>
        internal static string DecimalFieldFormatter_ToText_Format {
            get {
                return ResourceManager.GetString("DecimalFieldFormatter_ToText_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version declaration parameter value: &quot;{0}&quot;.
        /// </summary>
        internal static string DeclarationParser_Finish_DeclaredParametersInvalidVersionValue {
            get {
                return ResourceManager.GetString("DeclarationParser_Finish_DeclaredParametersInvalidVersionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration missing version parameter.
        /// </summary>
        internal static string DeclarationParser_Finish_DeclaredParametersMissingVersion {
            get {
                return ResourceManager.GetString("DeclarationParser_Finish_DeclaredParametersMissingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version declaration parameter is not first..
        /// </summary>
        internal static string DeclarationParser_Finish_DeclaredParametersVersionIsNotFirst {
            get {
                return ResourceManager.GetString("DeclarationParser_Finish_DeclaredParametersVersionIsNotFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration parameter missing value. Name: &quot;{0}&quot;.
        /// </summary>
        internal static string DeclarationParser_FinishLine_DeclarationParameterMissingValue {
            get {
                return ResourceManager.GetString("DeclarationParser_FinishLine_DeclarationParameterMissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration parameter name not terminated: &quot;{0}&quot;.
        /// </summary>
        internal static string DeclarationParser_FinishLine_DeclarationParameterNameNotTerminated {
            get {
                return ResourceManager.GetString("DeclarationParser_FinishLine_DeclarationParameterNameNotTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration parameter value not terminated. Name: &quot;{0}&quot;.
        /// </summary>
        internal static string DeclarationParser_FinishLine_DeclarationParameterValueNotTerminated {
            get {
                return ResourceManager.GetString("DeclarationParser_FinishLine_DeclarationParameterValueNotTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero length declaration parameter name.  Index: {0}.
        /// </summary>
        internal static string DeclarationParser_ParseChar_DeclarationParameterNameIsZeroLength {
            get {
                return ResourceManager.GetString("DeclarationParser_ParseChar_DeclarationParameterNameIsZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration parameter value is not quoted.  Name: &quot;{0}&quot;.
        /// </summary>
        internal static string DeclarationParser_ParseChar_DeclarationParameterValueNotQuoted {
            get {
                return ResourceManager.GetString("DeclarationParser_ParseChar_DeclarationParameterValueNotQuoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; is missing value.  Position: {1}.
        /// </summary>
        internal static string DeclaredParametersFormatter_ExtractValue_ParameterIsMissingValue {
            get {
                return ResourceManager.GetString("DeclaredParametersFormatter_ExtractValue_ParameterIsMissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for parameter &quot;{0}&quot; is missing closing quote.  Position: {1}.
        /// </summary>
        internal static string DeclaredParametersFormatter_ExtractValue_ValueForParameterIsMissingClosingQuote {
            get {
                return ResourceManager.GetString("DeclaredParametersFormatter_ExtractValue_ValueForParameterIsMissingClosingQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for parameter &quot;{0}&quot; is not quoted.  Position: {1}.
        /// </summary>
        internal static string DeclaredParametersFormatter_ExtractValue_ValueForParameterIsNotQuoted {
            get {
                return ResourceManager.GetString("DeclaredParametersFormatter_ExtractValue_ValueForParameterIsNotQuoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared parameter name cannot contain separator character: &quot;{0}&quot;.
        /// </summary>
        internal static string DeclaredParametersFormatter_ToText_NameContainsSeparatorCharacter {
            get {
                return ResourceManager.GetString("DeclaredParametersFormatter_ToText_NameContainsSeparatorCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter missing separator.  Position: {0}.
        /// </summary>
        internal static string DeclaredParametersFormatter_TryParse_ParameterMissingSeparator {
            get {
                return ResourceManager.GetString("DeclaredParametersFormatter_TryParse_ParameterMissingSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non white space character in field heading after quotes closed..
        /// </summary>
        internal static string DelimitedFieldParser_ParseChar_HeadingNonWhiteSpaceCharAfterQuotesClosed {
            get {
                return ResourceManager.GetString("DelimitedFieldParser_ParseChar_HeadingNonWhiteSpaceCharAfterQuotesClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non white space character in always quoted field heading before quotes opened..
        /// </summary>
        internal static string DelimitedFieldParser_ParseChar_HeadingNonWhiteSpaceCharBeforeQuotesOpened {
            get {
                return ResourceManager.GetString("DelimitedFieldParser_ParseChar_HeadingNonWhiteSpaceCharBeforeQuotesOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non white space character in field value after quotes closed..
        /// </summary>
        internal static string DelimitedFieldParser_ParseChar_ValueNonWhiteSpaceCharAfterQuotesClosed {
            get {
                return ResourceManager.GetString("DelimitedFieldParser_ParseChar_ValueNonWhiteSpaceCharAfterQuotesClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non white space character in always quoted field value before quotes opened..
        /// </summary>
        internal static string DelimitedFieldParser_ParseChar_ValueNonWhiteSpaceCharBeforeQuotesOpened {
            get {
                return ResourceManager.GetString("DelimitedFieldParser_ParseChar_ValueNonWhiteSpaceCharBeforeQuotesOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid AllowEndOfLineCharInQuotes: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveAllowEndOfLineCharInQuotes_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveAllowEndOfLineCharInQuotes_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid AllowIncompleteRecords: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveAllowIncompleteRecords_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveAllowIncompleteRecords_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Culture Name: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveCulture_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveCulture_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DelimiterChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveDelimiterChar_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveDelimiterChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid EndOfLineAutoWriteType: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveEndOfLineAutoWriteType_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveEndOfLineAutoWriteType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid EndOfLineChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveEndOfLineChar_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveEndOfLineChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid EndOfLineType: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveEndOfLineType_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveEndOfLineType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate explicit index in fields: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveFields_DuplicateExplicitIndexInFields {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveFields_DuplicateExplicitIndexInFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HeadingAlwaysWriteOptionalQuote: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveHeadingAlwaysWriteOptionalQuote_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveHeadingAlwaysWriteOptionalQuote_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HeadingConstraint: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveHeadingConstraint_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveHeadingConstraint_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HeadingEndOfValueChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveHeadingEndOfValueChar_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveHeadingEndOfValueChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HeadingLineCount: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveHeadingLineCount_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveHeadingLineCount_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HeadingPadAlignment: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveHeadingPadAlignment_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveHeadingPadAlignment_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HeadingPadChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveHeadingPadChar_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveHeadingPadChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HeadingPadCharType: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveHeadingPadCharType_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveHeadingPadCharType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HeadingQuotedType: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveHeadingQuotedType_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveHeadingQuotedType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HeadingTruncateChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveHeadingTruncateChar_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveHeadingTruncateChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HeadingTruncateType: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveHeadingTruncateType_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveHeadingTruncateType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HeadingWritePrefixSpace: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveHeadingWritePrefixSpace_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveHeadingWritePrefixSpace_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IgnoreBlankLines: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveIgnoreBlankLines_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveIgnoreBlankLines_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IgnoreExtraChars: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveIgnoreExtraChars_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveIgnoreExtraChars_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid LastLineEndedType: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveLastLineEndedType_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveLastLineEndedType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid legacy InvalidIncompleteRecordsAllowed &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveLegacyIncompleteRecordsAllowed_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveLegacyIncompleteRecordsAllowed_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid LineCommentChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveLineCommentChar_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveLineCommentChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MainHeadingLineIndex: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveMainHeadingLineIndex_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveMainHeadingLineIndex_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid QuoteChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveQuoteChar_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveQuoteChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid StuffedEmbeddedQuotes: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveStuffedEmbeddedQuotes_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveStuffedEmbeddedQuotes_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubstitutionChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveSubstitutionChar_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveSubstitutionChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubstitutionsEnabled: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldedTextReadElement_ResolveSubstitutionsEnabled_Invalid {
            get {
                return ResourceManager.GetString("FieldedTextReadElement_ResolveSubstitutionsEnabled_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No field constructor registered for DataType: {0}.
        /// </summary>
        internal static string FieldFactory_GetName_NoConstructorForDataType {
            get {
                return ResourceManager.GetString("FieldFactory_GetName_NoConstructorForDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field constructor with DataType name &quot;{0}&quot; already registered..
        /// </summary>
        internal static string FieldFactory_RegisterConstructor_NameAlreadyRegistered {
            get {
                return ResourceManager.GetString("FieldFactory_RegisterConstructor_NameAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field constructor with DataType &quot;{0}&quot; already registered..
        /// </summary>
        internal static string FieldFactory_RegisterConstructor_TypeAlreadyRegistered {
            get {
                return ResourceManager.GetString("FieldFactory_RegisterConstructor_TypeAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Boolean field styles: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveBooleanStyles_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveBooleanStyles_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Boolean field value: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveBooleanValue_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveBooleanValue_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Boolean value field : &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveBooleanValue_Missing {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveBooleanValue_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field constant: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveConstant_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveConstant_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DateTime field styles: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveDateTimeStyles_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveDateTimeStyles_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DateTime field value: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveDateTimeValue_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveDateTimeValue_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing DateTime value field : &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveDateTimeValue_Missing {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveDateTimeValue_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Decimal field styles: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveDecimalStyles_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveDecimalStyles_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Decimal field value: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveDecimalValue_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveDecimalValue_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Decimal value field : &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveDecimalValue_Missing {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveDecimalValue_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field FixedWidth: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveFixedWidth_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveFixedWidth_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Float field styles: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveFloatStyles_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveFloatStyles_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Float field value: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveFloatValue_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveFloatValue_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Float value field : &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveFloatValue_Missing {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveFloatValue_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field HeadingAlwaysWriteOptionalQuote: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveHeadingAlwaysWriteOptionalQuote_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveHeadingAlwaysWriteOptionalQuote_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field HeadingConstraint: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveHeadingConstraint_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveHeadingConstraint_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field HeadingEndOfValueChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveHeadingEndOfValueChar_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveHeadingEndOfValueChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field HeadingPadAlignment: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveHeadingPadAlignment_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveHeadingPadAlignment_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field HeadingPadChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveHeadingPadChar_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveHeadingPadChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field HeadingPadCharType: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveHeadingPadCharType_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveHeadingPadCharType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field HeadingQuotedType: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveHeadingQuotedType_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveHeadingQuotedType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field Headings: {0}.
        /// </summary>
        internal static string FieldReadElement_ResolveHeadings_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveHeadings_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field HeadingTruncateChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveHeadingTruncateChar_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveHeadingTruncateChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field HeadingTruncateType: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveHeadingTruncateType_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveHeadingTruncateType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field HeadingWritePrefixSpace: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveHeadingWritePrefixSpace_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveHeadingWritePrefixSpace_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field Id: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveId_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveId_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Integer field styles: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveIntegerStyles_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveIntegerStyles_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Integer field value: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveIntegerValue_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveIntegerValue_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Integer value field : &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveIntegerValue_Missing {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveIntegerValue_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field Null: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveNull_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveNull_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing String value field : &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveStringValue_Missing {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveStringValue_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field ValueAlwaysWriteOptionalQuote: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveValueAlwaysWriteOptionalQuote_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveValueAlwaysWriteOptionalQuote_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field ValueEndOfValueChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveValueEndOfValueChar_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveValueEndOfValueChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field ValueNullChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveValueNullChar_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveValueNullChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field ValuePadAlignment: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveValuePadAlignment_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveValuePadAlignment_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field ValuePadChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveValuePadChar_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveValuePadChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field ValuePadCharType: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveValuePadCharType_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveValuePadCharType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field ValueQuotedType: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveValueQuotedType_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveValueQuotedType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field ValueTruncateChar: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveValueTruncateChar_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveValueTruncateChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field ValueTruncateType: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveValueTruncateType_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveValueTruncateType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field ValueWritePrefixSpace: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveValueWritePrefixSpace_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveValueWritePrefixSpace_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field Width: &quot;{0}&quot;.
        /// </summary>
        internal static string FieldReadElement_ResolveWidth_Invalid {
            get {
                return ResourceManager.GetString("FieldReadElement_ResolveWidth_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field DataType.
        /// </summary>
        internal static string FieldReadElement_TryAddOrIgnoreAttribute_InvalidFieldDataType {
            get {
                return ResourceManager.GetString("FieldReadElement_TryAddOrIgnoreAttribute_InvalidFieldDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field Index.
        /// </summary>
        internal static string FieldReadElement_TryAddOrIgnoreAttribute_InvalidFieldIndex {
            get {
                return ResourceManager.GetString("FieldReadElement_TryAddOrIgnoreAttribute_InvalidFieldIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading width exceeded. Expected: {0} Actual: {1}.
        /// </summary>
        internal static string FixedWidthFieldParser_FinishText_HeadingWidthExceeded {
            get {
                return ResourceManager.GetString("FixedWidthFieldParser_FinishText_HeadingWidthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading width not reached. Expected: {0} Actual: {1}.
        /// </summary>
        internal static string FixedWidthFieldParser_FinishText_HeadingWidthNotReached {
            get {
                return ResourceManager.GetString("FixedWidthFieldParser_FinishText_HeadingWidthNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value width exceeded. Expected: {0} Actual: {1}.
        /// </summary>
        internal static string FixedWidthFieldParser_FinishText_ValueWidthExceeded {
            get {
                return ResourceManager.GetString("FixedWidthFieldParser_FinishText_ValueWidthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value width not reached. Expected: {0} Actual: {1}.
        /// </summary>
        internal static string FixedWidthFieldParser_FinishText_ValueWidthNotReached {
            get {
                return ResourceManager.GetString("FixedWidthFieldParser_FinishText_ValueWidthNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Float value: &quot;{0}&quot;.
        /// </summary>
        internal static string FloatFieldFormatter_Parse_Invalid {
            get {
                return ResourceManager.GetString("FloatFieldFormatter_Parse_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float formatting error: {0}.
        /// </summary>
        internal static string FloatFieldFormatter_ToText_Format {
            get {
                return ResourceManager.GetString("FloatFieldFormatter_ToText_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FtCommaText parse error: {0}.
        /// </summary>
        internal static string FtCommaText_Parse_Format {
            get {
                return ResourceManager.GetString("FtCommaText_Parse_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Integer.  Element: [{0}]: &quot;{1}&quot; .
        /// </summary>
        internal static string FtCommaText_TryParse_InvalidInteger {
            get {
                return ResourceManager.GetString("FtCommaText_TryParse_InvalidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes not closed in last element..
        /// </summary>
        internal static string FtCommaText_TryParse_QuotesNotClosedInLastElement {
            get {
                return ResourceManager.GetString("FtCommaText_TryParse_QuotesNotClosedInLastElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character after quoted element.  Position: {0}.
        /// </summary>
        internal static string FtCommaText_TryParse_UnexpectedCharAfterQuotedElement {
            get {
                return ResourceManager.GetString("FtCommaText_TryParse_UnexpectedCharAfterQuotedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataReader.GetByte not supported..
        /// </summary>
        internal static string FtDataReader_GetByte_NotSupported {
            get {
                return ResourceManager.GetString("FtDataReader_GetByte_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataReader.GetBytes not supported..
        /// </summary>
        internal static string FtDataReader_GetBytes_NotSupported {
            get {
                return ResourceManager.GetString("FtDataReader_GetBytes_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataReader.GetChar not supported..
        /// </summary>
        internal static string FtDataReader_GetChar_NotSupported {
            get {
                return ResourceManager.GetString("FtDataReader_GetChar_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataReader.GetChars not supported..
        /// </summary>
        internal static string FtDataReader_GetChars_NotSupported {
            get {
                return ResourceManager.GetString("FtDataReader_GetChars_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataReader.GetData not supported..
        /// </summary>
        internal static string FtDataReader_GetData_NotSupported {
            get {
                return ResourceManager.GetString("FtDataReader_GetData_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataReader.GetFloat not supported..
        /// </summary>
        internal static string FtDataReader_GetFloat_NotSupported {
            get {
                return ResourceManager.GetString("FtDataReader_GetFloat_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataReader.GetGuid not supported..
        /// </summary>
        internal static string FtDataReader_GetGuid_NotSupported {
            get {
                return ResourceManager.GetString("FtDataReader_GetGuid_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataReader.GetInt16 not supported..
        /// </summary>
        internal static string FtDataReader_GetInt16_NotSupported {
            get {
                return ResourceManager.GetString("FtDataReader_GetInt16_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataReader.GetInt32 not supported..
        /// </summary>
        internal static string FtDataReader_GetInt32_NotSupported {
            get {
                return ResourceManager.GetString("FtDataReader_GetInt32_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load delimited value error: {0}.
        /// </summary>
        internal static string FtField_LoadDelimitedValue_Prefix {
            get {
                return ResourceManager.GetString("FtField_LoadDelimitedValue_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load fixed width value Error: {0}.
        /// </summary>
        internal static string FtField_LoadFixedWidthValue_Prefix {
            get {
                return ResourceManager.GetString("FtField_LoadFixedWidthValue_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All constant violation. Index: {0}.
        /// </summary>
        internal static string FtField_LoadHeading_AllConstantViolation {
            get {
                return ResourceManager.GetString("FtField_LoadHeading_AllConstantViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main constant violation.
        /// </summary>
        internal static string FtField_LoadHeading_MainConstantViolation {
            get {
                return ResourceManager.GetString("FtField_LoadHeading_MainConstantViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name constant violation.
        /// </summary>
        internal static string FtField_LoadHeading_NameConstantViolation {
            get {
                return ResourceManager.GetString("FtField_LoadHeading_NameConstantViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected constant non null value but loaded null value ..
        /// </summary>
        internal static string FtField_LoadNullValue_ConstantNonNullValueExpected {
            get {
                return ResourceManager.GetString("FtField_LoadNullValue_ConstantNonNullValueExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set ValueText error: {0}.
        /// </summary>
        internal static string FtField_SetAsNonNullValueText_Prefix {
            get {
                return ResourceManager.GetString("FtField_SetAsNonNullValueText_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to set null in constant field: &quot;{0}&quot;.
        /// </summary>
        internal static string FtField_SetNull_Constant {
            get {
                return ResourceManager.GetString("FtField_SetNull_Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text truncation: &quot;{0}&quot;.
        /// </summary>
        internal static string FtField_TruncateText_TextTruncation {
            get {
                return ResourceManager.GetString("FtField_TruncateText_TextTruncation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null value in field: &quot;{0}&quot;.
        /// </summary>
        internal static string FtGenericField_GetValueOrThrowNull_AttemptToGetValueFromNullField {
            get {
                return ResourceManager.GetString("FtGenericField_GetValueOrThrowNull_AttemptToGetValueFromNullField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected constant null value but loaded non null value : {0}.
        /// </summary>
        internal static string FtGenericField_LoadNonNullValue_ConstantNullValueExpected {
            get {
                return ResourceManager.GetString("FtGenericField_LoadNonNullValue_ConstantNullValueExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant value mismatch: {0}.
        /// </summary>
        internal static string FtGenericField_LoadNonNullValue_ConstantValueMismatch {
            get {
                return ResourceManager.GetString("FtGenericField_LoadNonNullValue_ConstantValueMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to set value in constant field: &quot;{0}&quot;.
        /// </summary>
        internal static string FtGenericField_SetValue_Constant {
            get {
                return ResourceManager.GetString("FtGenericField_SetValue_Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: DelimiterChar and SubstitutionChar must be different if substitutions.
        /// </summary>
        internal static string FtMeta_Validate_DelimiterCharAndSubstitutionCharMustBeDifferent {
            get {
                return ResourceManager.GetString("FtMeta_Validate_DelimiterCharAndSubstitutionCharMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: Duplicate sequence name: &quot;{0}&quot;.
        /// </summary>
        internal static string FtMeta_Validate_DuplicateSequenceName {
            get {
                return ResourceManager.GetString("FtMeta_Validate_DuplicateSequenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: LineCommentChar and DelimiterChar must be different.
        /// </summary>
        internal static string FtMeta_Validate_LineCommentCharAndDelimiterCharMustBeDifferent {
            get {
                return ResourceManager.GetString("FtMeta_Validate_LineCommentCharAndDelimiterCharMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: LineCommentChar and SubstitutionChar must be different if substitutions.
        /// </summary>
        internal static string FtMeta_Validate_LineCommentCharAndSubstitutionCharMustBeDifferent {
            get {
                return ResourceManager.GetString("FtMeta_Validate_LineCommentCharAndSubstitutionCharMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: More than one root sequence:  &quot;{0}&quot;, &quot;{1}&quot;.
        /// </summary>
        internal static string FtMeta_Validate_MoreThanOneRootSequence {
            get {
                return ResourceManager.GetString("FtMeta_Validate_MoreThanOneRootSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: Must have at least one field..
        /// </summary>
        internal static string FtMeta_Validate_MustHaveAtLeastOneField {
            get {
                return ResourceManager.GetString("FtMeta_Validate_MustHaveAtLeastOneField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: QuoteChar and DelimiterChar must be different..
        /// </summary>
        internal static string FtMeta_Validate_QuoteCharAndDelimiterCharMustBeDifferent {
            get {
                return ResourceManager.GetString("FtMeta_Validate_QuoteCharAndDelimiterCharMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: QuoteChar and LineCommentChar must be different..
        /// </summary>
        internal static string FtMeta_Validate_QuoteCharAndLineCommentCharMustBeDifferent {
            get {
                return ResourceManager.GetString("FtMeta_Validate_QuoteCharAndLineCommentCharMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: QuoteChar and SubstitutionChar must be different if substitutions are enabled..
        /// </summary>
        internal static string FtMeta_Validate_QuoteCharAndSubstitutionCharMustBeDifferent {
            get {
                return ResourceManager.GetString("FtMeta_Validate_QuoteCharAndSubstitutionCharMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence item with constant field has redirects.  Sequence name: &quot;{0}&quot; Item index: {1}.
        /// </summary>
        internal static string FtMeta_Validate_SequenceItemWithConstantFieldHasRedirects {
            get {
                return ResourceManager.GetString("FtMeta_Validate_SequenceItemWithConstantFieldHasRedirects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Item with null field.  Sequence name: &quot;{0}&quot; Item index: {1}.
        /// </summary>
        internal static string FtMeta_Validate_SequenceItemWithNullField {
            get {
                return ResourceManager.GetString("FtMeta_Validate_SequenceItemWithNullField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: DelimiterChar cannot be same as end of line char: {0}.
        /// </summary>
        internal static string FtMeta_ValidateEndOfLineTypeChar_DelimiterCharCannotBeAnEndOfLineChar {
            get {
                return ResourceManager.GetString("FtMeta_ValidateEndOfLineTypeChar_DelimiterCharCannotBeAnEndOfLineChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: If HeadingLineCount &gt; 0, HeadingEndOfValueChar cannot be same as end of line char: {0}.
        /// </summary>
        internal static string FtMeta_ValidateEndOfLineTypeChar_HeadingEndOfValueCharCannotBeAnEndOfLineChar {
            get {
                return ResourceManager.GetString("FtMeta_ValidateEndOfLineTypeChar_HeadingEndOfValueCharCannotBeAnEndOfLineChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: If HeadingLineCount &gt; 0, HeadingPadChar cannot be same as end of line char: {0}.
        /// </summary>
        internal static string FtMeta_ValidateEndOfLineTypeChar_HeadingPadCharCannotBeAnEndOfLineChar {
            get {
                return ResourceManager.GetString("FtMeta_ValidateEndOfLineTypeChar_HeadingPadCharCannotBeAnEndOfLineChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: If HeadingLineCount &gt; 0, HeadingTruncateChar cannot be same as end of line char: {0}.
        /// </summary>
        internal static string FtMeta_ValidateEndOfLineTypeChar_HeadingTruncateCharCannotBeAnEndOfLineChar {
            get {
                return ResourceManager.GetString("FtMeta_ValidateEndOfLineTypeChar_HeadingTruncateCharCannotBeAnEndOfLineChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: LineCommentChar cannot be same as end of line char : {0}.
        /// </summary>
        internal static string FtMeta_ValidateEndOfLineTypeChar_LineCommentCharCannotBeAnEndOfLineChar {
            get {
                return ResourceManager.GetString("FtMeta_ValidateEndOfLineTypeChar_LineCommentCharCannotBeAnEndOfLineChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: QuoteChar cannot be same as end of line char: {0}.
        /// </summary>
        internal static string FtMeta_ValidateEndOfLineTypeChar_QuoteCharCannotBeAnEndOfLineChar {
            get {
                return ResourceManager.GetString("FtMeta_ValidateEndOfLineTypeChar_QuoteCharCannotBeAnEndOfLineChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: If substitutions are enabled, SubstitutionChar cannot be same as end of line char: {0}.
        /// </summary>
        internal static string FtMeta_ValidateEndOfLineTypeChar_SubstitutionCharCannotBeAnEndOfLineChar {
            get {
                return ResourceManager.GetString("FtMeta_ValidateEndOfLineTypeChar_SubstitutionCharCannotBeAnEndOfLineChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: FixedWidth field (&quot;{0}&quot;) HeadingEndOfValueChar cannot be same as end of line char: {1}.
        /// </summary>
        internal static string FtMetaField_ValidateEndOfLineTypeChar_HeadingEndOfValueCharCannotBeAnEndOfLineChar {
            get {
                return ResourceManager.GetString("FtMetaField_ValidateEndOfLineTypeChar_HeadingEndOfValueCharCannotBeAnEndOfLineCha" +
                        "r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: FixedWidth field (&quot;{0}&quot;) HeadingPadChar cannot be same as end of line char: {1}.
        /// </summary>
        internal static string FtMetaField_ValidateEndOfLineTypeChar_HeadingPadCharCannotBeAnEndOfLineChar {
            get {
                return ResourceManager.GetString("FtMetaField_ValidateEndOfLineTypeChar_HeadingPadCharCannotBeAnEndOfLineChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: FixedWidth field (&quot;{0}&quot;) HeadingTruncateChar cannot be same as end of line char: {1}.
        /// </summary>
        internal static string FtMetaField_ValidateEndOfLineTypeChar_HeadingTruncateCharCannotBeAnEndOfLineChar {
            get {
                return ResourceManager.GetString("FtMetaField_ValidateEndOfLineTypeChar_HeadingTruncateCharCannotBeAnEndOfLineChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: FixedWidth field (&quot;{0}&quot;) ValueEndOfValueChar cannot be same as end of line char: {1}.
        /// </summary>
        internal static string FtMetaField_ValidateEndOfLineTypeChar_ValueEndOfValueCharCannotBeAnEndOfLineChar {
            get {
                return ResourceManager.GetString("FtMetaField_ValidateEndOfLineTypeChar_ValueEndOfValueCharCannotBeAnEndOfLineChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: FixedWidth field (&quot;{0}&quot;) ValueNullChar cannot be same as end of line char: {1}.
        /// </summary>
        internal static string FtMetaField_ValidateEndOfLineTypeChar_ValueNullCharCannotBeAnEndOfLineChar {
            get {
                return ResourceManager.GetString("FtMetaField_ValidateEndOfLineTypeChar_ValueNullCharCannotBeAnEndOfLineChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: FixedWidth field (&quot;{0}&quot;) ValuePadChar cannot be same as end of line char: {1}.
        /// </summary>
        internal static string FtMetaField_ValidateEndOfLineTypeChar_ValuePadCharCannotBeAnEndOfLineChar {
            get {
                return ResourceManager.GetString("FtMetaField_ValidateEndOfLineTypeChar_ValuePadCharCannotBeAnEndOfLineChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meta: FixedWidth field (&quot;{0}&quot;) ValueTruncateChar cannot be same as end of line char: {1}.
        /// </summary>
        internal static string FtMetaField_ValidateEndOfLineTypeChar_ValueTruncateCharCannotBeAnEndOfLineChar {
            get {
                return ResourceManager.GetString("FtMetaField_ValidateEndOfLineTypeChar_ValueTruncateCharCannotBeAnEndOfLineChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid standard DataType: {0}.
        /// </summary>
        internal static string FtStandardDataType_ToName_InvalidType {
            get {
                return ResourceManager.GetString("FtStandardDataType_ToName_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid standard SequenceRedirectType: {0}.
        /// </summary>
        internal static string FtStandardSequenceRedirectType_ToName_InvalidType {
            get {
                return ResourceManager.GetString("FtStandardSequenceRedirectType_ToName_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid standard Boolean text: &quot;{0}&quot;.
        /// </summary>
        internal static string FtStandardText_ParseBoolean_Invalid {
            get {
                return ResourceManager.GetString("FtStandardText_ParseBoolean_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid standard Char text: &quot;{0}&quot;.
        /// </summary>
        internal static string FtStandardText_ParseChar_Invalid {
            get {
                return ResourceManager.GetString("FtStandardText_ParseChar_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid standard DateTime text: &quot;{0}&quot;.
        /// </summary>
        internal static string FtStandardText_ParseDateTime_Invalid {
            get {
                return ResourceManager.GetString("FtStandardText_ParseDateTime_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid standard Decimal text: &quot;{0}&quot;.
        /// </summary>
        internal static string FtStandardText_ParseDecimal_Invalid {
            get {
                return ResourceManager.GetString("FtStandardText_ParseDecimal_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid standard Float text: &quot;{0}&quot;.
        /// </summary>
        internal static string FtStandardText_ParseFloat_Invalid {
            get {
                return ResourceManager.GetString("FtStandardText_ParseFloat_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid standard Int32 text: &quot;{0}&quot;.
        /// </summary>
        internal static string FtStandardText_ParseInt32_Invalid {
            get {
                return ResourceManager.GetString("FtStandardText_ParseInt32_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid standard Integer text: &quot;{0}&quot;.
        /// </summary>
        internal static string FtStandardText_ParseInteger_Invalid {
            get {
                return ResourceManager.GetString("FtStandardText_ParseInteger_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading line does not have enough fields.  Count: {0} Expected: {1}.
        /// </summary>
        internal static string HeadingLineRecordParser_Finish_HeadingLineNotEnoughFields {
            get {
                return ResourceManager.GetString("HeadingLineRecordParser_Finish_HeadingLineNotEnoughFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record does not have enough fields.  Count: {0} Expected: {1}.
        /// </summary>
        internal static string HeadingLineRecordParser_Finish_RecordNotEnoughFields {
            get {
                return ResourceManager.GetString("HeadingLineRecordParser_Finish_RecordNotEnoughFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading line has too many fields. Maximum: {0}.
        /// </summary>
        internal static string HeadingLineRecordParser_ParseChar_HeadingLineTooManyFields {
            get {
                return ResourceManager.GetString("HeadingLineRecordParser_ParseChar_HeadingLineTooManyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has too many fields. Maximum: {0}.
        /// </summary>
        internal static string HeadingLineRecordParser_ParseChar_RecordTooManyFields {
            get {
                return ResourceManager.GetString("HeadingLineRecordParser_ParseChar_RecordTooManyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid integer value: &quot;{0}&quot;.
        /// </summary>
        internal static string IntegerFieldFormatter_Parse_Invalid {
            get {
                return ResourceManager.GetString("IntegerFieldFormatter_Parse_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer formatting error: {0}.
        /// </summary>
        internal static string IntegerFieldFormatter_ToText_Format {
            get {
                return ResourceManager.GetString("IntegerFieldFormatter_ToText_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Internal error: {0} Member: \&quot;{1}\&quot; File: \&quot;{2}\&quot; Line: {3}.
        /// </summary>
        internal static string InternalExceptionMessage {
            get {
                return ResourceManager.GetString("InternalExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last line not ended..
        /// </summary>
        internal static string LineParser_FinishLastLine_AlwaysEndedButIn {
            get {
                return ResourceManager.GetString("LineParser_FinishLastLine_AlwaysEndedButIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last line ended..
        /// </summary>
        internal static string LineParser_FinishLastLine_NeverEndedButOut {
            get {
                return ResourceManager.GetString("LineParser_FinishLastLine_NeverEndedButOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sequence item field index: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceItemReadElement_ResolveFieldIndex_Invalid {
            get {
                return ResourceManager.GetString("SequenceItemReadElement_ResolveFieldIndex_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence item missing field Index..
        /// </summary>
        internal static string SequenceItemReadElement_ResolveFieldIndex_Missing {
            get {
                return ResourceManager.GetString("SequenceItemReadElement_ResolveFieldIndex_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence item field index out of range: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceItemReadElement_ResolveFieldIndex_OutOfRange {
            get {
                return ResourceManager.GetString("SequenceItemReadElement_ResolveFieldIndex_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence item sequence redirects have duplicate explicit index: {0}.
        /// </summary>
        internal static string SequenceItemReadElement_ResolveRedirects_DuplicateExplicitIndex {
            get {
                return ResourceManager.GetString("SequenceItemReadElement_ResolveRedirects_DuplicateExplicitIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sequence item index: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceItemReadElement_TryAddOrIgnoreAttribute_Invalid {
            get {
                return ResourceManager.GetString("SequenceItemReadElement_TryAddOrIgnoreAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sequence field indices: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceReadElement_ResolveFieldIndices_Invalid {
            get {
                return ResourceManager.GetString("SequenceReadElement_ResolveFieldIndices_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence items have duplicate explicit index: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceReadElement_ResolveItemsTo_DuplicateExplicitIndex {
            get {
                return ResourceManager.GetString("SequenceReadElement_ResolveItemsTo_DuplicateExplicitIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate sequence name: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceReadElement_ResolveName_Duplicate {
            get {
                return ResourceManager.GetString("SequenceReadElement_ResolveName_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence missing name.
        /// </summary>
        internal static string SequenceReadElement_ResolveName_Missing {
            get {
                return ResourceManager.GetString("SequenceReadElement_ResolveName_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sequence root: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceReadElement_ResolveRoot_Invalid {
            get {
                return ResourceManager.GetString("SequenceReadElement_ResolveRoot_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SequenceRedirect constructor registered for type: {0}.
        /// </summary>
        internal static string SequenceRedirectFactory_GetName_NoConstructorForType {
            get {
                return ResourceManager.GetString("SequenceRedirectFactory_GetName_NoConstructorForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceRedirect constructor with type name &quot;{0}&quot; already registered.
        /// </summary>
        internal static string SequenceRedirectFactory_RegisterConstructor_NameAlreadyRegistered {
            get {
                return ResourceManager.GetString("SequenceRedirectFactory_RegisterConstructor_NameAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceRedirect constructor with type &quot;{0}&quot; already registered.
        /// </summary>
        internal static string SequenceRedirectFactory_RegisterConstructor_TypeAlreadyRegistered {
            get {
                return ResourceManager.GetString("SequenceRedirectFactory_RegisterConstructor_TypeAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Boolean sequence redirect value: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveBooleanValue_Invalid {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveBooleanValue_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean sequence redirect missing value. Redirect type: &quot;{0}&quot; .
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveBooleanValue_Missing {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveBooleanValue_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CaseInsensitiveString sequence Redirect value: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveCaseInsensitiveStringValue_Invalid {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveCaseInsensitiveStringValue_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaseInsensitiveString sequence redirect missing value. Redirect type: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveCaseInsensitiveStringValue_Missing {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveCaseInsensitiveStringValue_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date sequence redirect value: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveDateValue_Invalid {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveDateValue_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date sequence redirect missing value. Redirect type: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveDateValue_Missing {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveDateValue_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ExactDateTime sequence redirect value: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveExactDateTimeValue_Invalid {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveExactDateTimeValue_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExactDateTime sequence redirect missing value. Redirect type: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveExactDateTimeValue_Missing {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveExactDateTimeValue_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ExactDecimal sequence redirect value: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveExactDecimalValue_Invalid {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveExactDecimalValue_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExactDecimal sequence redirect missing value. Redirect type: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveExactDecimalValue_Missing {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveExactDecimalValue_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ExactFloat sequence redirect value: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveExactFloatValue_Invalid {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveExactFloatValue_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExactFloat sequence redirect missing value. Redirect type: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveExactFloatValue_Missing {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveExactFloatValue_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ExactInteger sequence redirect value: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveExactIntegerValue_Invalid {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveExactIntegerValue_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExactInteger sequence redirect missing value. Redirect type: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveExactIntegerValue_Missing {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveExactIntegerValue_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ExactString sequence redirect value: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveExactStringValue_Invalid {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveExactStringValue_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExactString sequence redirect missing value. Redirect type: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveExactStringValue_Missing {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveExactStringValue_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sequence redirect invokation delay: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveInvokationDelay_Invalid {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveInvokationDelay_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence redirect missing sequence name. Redirect type: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveSequenceName_Missing {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveSequenceName_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence redirect specifies sequence name which does not exist. Name &quot;{0}&quot;. Redirect Type &quot;{1}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_ResolveSequenceName_NotExist {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_ResolveSequenceName_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sequence redirect index: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_TryAddOrIgnoreAttribute_InvalidIndex {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_TryAddOrIgnoreAttribute_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sequence redirect type: &quot;{0}&quot;.
        /// </summary>
        internal static string SequenceRedirectReadElement_TryAddOrIgnoreAttribute_InvalidType {
            get {
                return ResourceManager.GetString("SequenceRedirectReadElement_TryAddOrIgnoreAttribute_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field not found. Id: {0}.
        /// </summary>
        internal static string SerializationCore_GetOrdinal_IdNotFound {
            get {
                return ResourceManager.GetString("SerializationCore_GetOrdinal_IdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field not found: Name: {0}.
        /// </summary>
        internal static string SerializationCore_GetOrdinal_NameNotFound {
            get {
                return ResourceManager.GetString("SerializationCore_GetOrdinal_NameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing second line..
        /// </summary>
        internal static string SerializationReader_Finish_DeclarationMissingSecondLine {
            get {
                return ResourceManager.GetString("SerializationReader_Finish_DeclarationMissingSecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBoolean cannot get value from field type: &quot;{0}&quot;.
        /// </summary>
        internal static string SerializationReader_GetBoolean_InvalidCast {
            get {
                return ResourceManager.GetString("SerializationReader_GetBoolean_InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetDateTime cannot get value from field type: &quot;{0}&quot;.
        /// </summary>
        internal static string SerializationReader_GetDateTime_InvalidCast {
            get {
                return ResourceManager.GetString("SerializationReader_GetDateTime_InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetDecimal cannot get value from field type: &quot;{0}&quot;.
        /// </summary>
        internal static string SerializationReader_GetDecimal_InvalidCast {
            get {
                return ResourceManager.GetString("SerializationReader_GetDecimal_InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetDouble cannot get value from field type: &quot;{0}&quot;.
        /// </summary>
        internal static string SerializationReader_GetDouble_InvalidCast {
            get {
                return ResourceManager.GetString("SerializationReader_GetDouble_InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &quot;{0}&quot; not found..
        /// </summary>
        internal static string SerializationReader_GetField_IndexOutOfRange {
            get {
                return ResourceManager.GetString("SerializationReader_GetField_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetInt64 cannot get value from field type: &quot;{0}&quot;.
        /// </summary>
        internal static string SerializationReader_GetInt64_InvalidCast {
            get {
                return ResourceManager.GetString("SerializationReader_GetInt64_InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetString cannot get value from field type: &quot;{0}&quot;.
        /// </summary>
        internal static string SerializationReader_GetString_InvalidCast {
            get {
                return ResourceManager.GetString("SerializationReader_GetString_InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank records not allowed..
        /// </summary>
        internal static string SerializationReader_ParseChar_BlankRecordsNotAllowed {
            get {
                return ResourceManager.GetString("SerializationReader_ParseChar_BlankRecordsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded meta line not blank or comment..
        /// </summary>
        internal static string SerializationReader_ParseChar_EmbeddedMetaLineNotBlankOrComment {
            get {
                return ResourceManager.GetString("SerializationReader_ParseChar_EmbeddedMetaLineNotBlankOrComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBoolean cannot set value for field type: &quot;{0}&quot;.
        /// </summary>
        internal static string SerializationWriter_SetBoolean_InvalidCast {
            get {
                return ResourceManager.GetString("SerializationWriter_SetBoolean_InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetDateTime cannot set value for field type: &quot;{0}&quot;.
        /// </summary>
        internal static string SerializationWriter_SetDateTime_InvalidCast {
            get {
                return ResourceManager.GetString("SerializationWriter_SetDateTime_InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetDecimal cannot set value for field type: &quot;{0}&quot;.
        /// </summary>
        internal static string SerializationWriter_SetDecimal_InvalidCast {
            get {
                return ResourceManager.GetString("SerializationWriter_SetDecimal_InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetDouble cannot set value for field type: &quot;{0}&quot;.
        /// </summary>
        internal static string SerializationWriter_SetDouble_InvalidCast {
            get {
                return ResourceManager.GetString("SerializationWriter_SetDouble_InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetInt64 cannot set value for field type: &quot;{0}&quot;.
        /// </summary>
        internal static string SerializationWriter_SetInt64_InvalidCast {
            get {
                return ResourceManager.GetString("SerializationWriter_SetInt64_InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetString cannot set value for field type: &quot;{0}&quot;.
        /// </summary>
        internal static string SerializationWriter_SetString_InvalidCast {
            get {
                return ResourceManager.GetString("SerializationWriter_SetString_InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values length {0} exceeded field count {1}.
        /// </summary>
        internal static string SerializationWriter_SetValues_ValuesLengthExceededFieldCount {
            get {
                return ResourceManager.GetString("SerializationWriter_SetValues_ValuesLengthExceededFieldCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header already written..
        /// </summary>
        internal static string SerializationWriter_WriteHeader_HeaderAlreadyWritten {
            get {
                return ResourceManager.GetString("SerializationWriter_WriteHeader_HeaderAlreadyWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid substitution token: &quot;{0}&quot;.
        /// </summary>
        internal static string SubstitutionReadElement_ResolveToken_Invalid {
            get {
                return ResourceManager.GetString("SubstitutionReadElement_ResolveToken_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitution missing token. Type: &quot;{0}&quot;.
        /// </summary>
        internal static string SubstitutionReadElement_ResolveToken_Missing {
            get {
                return ResourceManager.GetString("SubstitutionReadElement_ResolveToken_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid substitution type: &quot;{0}&quot;.
        /// </summary>
        internal static string SubstitutionReadElement_ResolveType_Invalid {
            get {
                return ResourceManager.GetString("SubstitutionReadElement_ResolveType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String substitution missing value. Token: &quot;{0}&quot;.
        /// </summary>
        internal static string SubstitutionReadElement_ResolveValue_MissingForString {
            get {
                return ResourceManager.GetString("SubstitutionReadElement_ResolveValue_MissingForString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Error. Name: &quot;{0}&quot; Value: &quot;{1}&quot; Description: &quot;{2}&quot;.
        /// </summary>
        internal static string XmlMetaSerializationReader_Read_AttributeError {
            get {
                return ResourceManager.GetString("XmlMetaSerializationReader_Read_AttributeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete XML stream..
        /// </summary>
        internal static string XmlMetaSerializationReader_Read_IncompleteXmlStream {
            get {
                return ResourceManager.GetString("XmlMetaSerializationReader_Read_IncompleteXmlStream", resourceCulture);
            }
        }
    }
}
